using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;

namespace Glai.ECS.SourceGen
{
    [Generator]
    public sealed class GenericTemplateGenerator : IIncrementalGenerator
    {
        static readonly Regex TemplateRegex = new Regex(
            @"/\*\s*\*?\s*@template\s+(?<name>\w+)\s*\r?\n(?<body>[\s\S]*?)\*/",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        static readonly Regex EachTypesRegex = new Regex(
            @"\{\{#each\s+(?<slot>\w+)\s*\}\}(?<inner>[\s\S]*?)\{\{/each\}\}",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        static readonly Regex JoinBlockRegex = new Regex(
            @"\{\{#join(?:\s+(?<slot>\w+))?\s+(?<separator>""(?:[^""\\]|\\.)*"")\s*\}\}(?<inner>[\s\S]*?)\{\{/join\}\}",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        static readonly Regex JoinMacroRegex = new Regex(
            @"\{\{\s*(?<kind>ARGS|REF_ARGS)(?:\s+(?<slot>\w+))?\s*\}\}",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        static readonly Regex MetadataLineRegex = new Regex(
            @"^(?<key>[\w\.]+):\s*(?<value>.*)$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        static readonly Regex ArityExpressionRegex = new Regex(
            @"^(?<target>arity|n)\s*(?<op>[\+\-])\s*(?<value>\d+)$",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        static readonly HashSet<string> TopLevelKeys = new HashSet<string>(StringComparer.Ordinal)
        {
            "hintName",
            "namespace",
            "container",
            "maxArity",
            "usings",
            "slot"
        };

        static readonly HashSet<string> SlotKeys = new HashSet<string>(StringComparer.Ordinal)
        {
            "count",
            "constraint",
            "type",
            "param",
            "local",
            "paramType"
        };

        static readonly DiagnosticDescriptor InvalidTemplateDescriptor = new DiagnosticDescriptor(
            id: "GTG001",
            title: "Invalid template metadata",
            messageFormat: "Template '{0}' is invalid: {1}",
            category: "GenericTemplateGenerator",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        static readonly DiagnosticDescriptor DuplicateHintNameDescriptor = new DiagnosticDescriptor(
            id: "GTG002",
            title: "Duplicate template hint name",
            messageFormat: "Template '{0}' uses duplicate hintName '{1}'.",
            category: "GenericTemplateGenerator",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) => Emit(spc, compilation));
        }

        static void Emit(SourceProductionContext spc, Compilation compilation)
        {
            List<TemplateModel> templates = CollectTemplates(compilation, spc);
            var hintNames = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < templates.Count; i++)
            {
                TemplateModel template = templates[i];
                if (!hintNames.Add(template.HintName))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(DuplicateHintNameDescriptor, Location.None, template.TemplateName, template.HintName));
                    continue;
                }

                EmitTemplate(spc, template);
            }
        }

        static void EmitTemplate(SourceProductionContext spc, TemplateModel template)
        {
            if (template.MaxArity < 1)
            {
                return;
            }

            var sb = new StringBuilder(4096);
            sb.AppendLine("// <auto-generated/>");
            for (int i = 0; i < template.Usings.Length; i++)
            {
                sb.Append("using ").Append(template.Usings[i]).AppendLine(";");
            }

            sb.Append("namespace ").AppendLine(template.NamespaceName);
            sb.AppendLine("{");
            sb.Append("    ").AppendLine(template.ContainerDeclaration);
            sb.AppendLine("    {");

            int emittedCount = 0;
            for (int arity = 1; arity <= template.MaxArity; arity++)
            {
                if (!TryRenderMethod(template, arity, out string rendered))
                {
                    continue;
                }

                if (emittedCount > 0)
                {
                    sb.AppendLine();
                }

                foreach (string line in SplitLines(rendered))
                {
                    if (line.Length == 0)
                    {
                        sb.AppendLine();
                    }
                    else
                    {
                        sb.Append("        ").AppendLine(line);
                    }
                }

                emittedCount++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            spc.AddSource(template.HintName, sb.ToString());
        }

        static List<TemplateModel> CollectTemplates(Compilation compilation, SourceProductionContext spc)
        {
            var templates = new List<TemplateModel>();

            foreach (var syntaxTree in compilation.SyntaxTrees)
            {
                string sourceText = syntaxTree.GetText().ToString();
                var matches = TemplateRegex.Matches(sourceText);
                foreach (Match match in matches)
                {
                    if (!match.Success)
                    {
                        continue;
                    }

                    string templateName = match.Groups["name"].Value;
                    string body = StripCommentPrefix(match.Groups["body"].Value);

                    if (TryBuildTemplate(templateName, body, out TemplateModel template, out string error))
                    {
                        templates.Add(template);
                        continue;
                    }

                    spc.ReportDiagnostic(Diagnostic.Create(InvalidTemplateDescriptor, Location.None, templateName, error));
                }
            }

            return templates;
        }

        static bool TryBuildTemplate(string templateName, string input, out TemplateModel template, out string error)
        {
            template = default;
            error = string.Empty;

            string[] lines = SplitLines(input).ToArray();
            var metadata = new Dictionary<string, string>(StringComparer.Ordinal);
            var slotBuilders = new List<SlotBuilder>();
            SlotBuilder? currentSlot = null;

            int bodyStart = -1;
            for (int i = 0; i < lines.Length; i++)
            {
                string line = lines[i];
                string trimmed = line.Trim();
                if (trimmed.Length == 0)
                {
                    continue;
                }

                Match match = MetadataLineRegex.Match(trimmed);
                if (!match.Success)
                {
                    bodyStart = i;
                    break;
                }

                string key = match.Groups["key"].Value;
                string value = match.Groups["value"].Value.Trim();

                if (key.Equals("slot", StringComparison.Ordinal))
                {
                    if (value.Length == 0)
                    {
                        error = "Property 'slot' must have a value.";
                        return false;
                    }

                    currentSlot = new SlotBuilder(value);
                    slotBuilders.Add(currentSlot.Value);
                    continue;
                }

                if (currentSlot.HasValue && SlotKeys.Contains(key))
                {
                    SlotBuilder builder = currentSlot.Value;
                    builder.Set(key, value);
                    currentSlot = builder;
                    slotBuilders[slotBuilders.Count - 1] = builder;
                    continue;
                }

                if (!TopLevelKeys.Contains(key))
                {
                    bodyStart = i;
                    break;
                }

                metadata[key] = value;
            }

            if (bodyStart < 0)
            {
                error = "Template body is missing.";
                return false;
            }

            if (!TryGetRequired(metadata, "hintName", out string hintName, out error)) return false;
            if (!TryGetRequired(metadata, "namespace", out string namespaceName, out error)) return false;
            if (!TryGetRequired(metadata, "container", out string containerDeclaration, out error)) return false;
            if (!TryGetRequiredInt(metadata, "maxArity", out int maxArity, out error) || maxArity < 1)
            {
                error = "Property 'maxArity' must be an integer greater than zero.";
                return false;
            }

            if (slotBuilders.Count == 0)
            {
                error = "At least one 'slot' block is required.";
                return false;
            }

            var slotModels = new List<SlotModel>(slotBuilders.Count);
            var slotNames = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < slotBuilders.Count; i++)
            {
                SlotModel slot = slotBuilders[i].Build();
                if (!slotNames.Add(slot.Name))
                {
                    error = $"Duplicate slot '{slot.Name}'.";
                    return false;
                }

                slotModels.Add(slot);
            }

            string[] usings = ParseList(GetValue(metadata, "usings", string.Empty));
            string body = string.Join("\n", lines, bodyStart, lines.Length - bodyStart).Trim();
            template = new TemplateModel(templateName, hintName, namespaceName, containerDeclaration, usings, body, maxArity, slotModels);
            return true;
        }

        static bool TryGetRequired(Dictionary<string, string> metadata, string key, out string value, out string error)
        {
            error = string.Empty;
            if (metadata.TryGetValue(key, out value) && value.Length > 0)
            {
                return true;
            }

            error = $"Missing required property '{key}'.";
            value = string.Empty;
            return false;
        }

        static bool TryGetRequiredInt(Dictionary<string, string> metadata, string key, out int value, out string error)
        {
            error = string.Empty;
            value = default;
            if (!metadata.TryGetValue(key, out string raw) || raw.Length == 0 || !int.TryParse(raw, out value))
            {
                error = $"Missing required property '{key}'.";
                return false;
            }

            return true;
        }

        static string GetValue(Dictionary<string, string> metadata, string key, string fallback)
        {
            if (metadata.TryGetValue(key, out string value))
            {
                return value;
            }

            return fallback;
        }

        static bool TryRenderMethod(TemplateModel template, int arity, out string rendered)
        {
            var allSlots = new List<TypeSlotModel>();
            var slotsByName = new Dictionary<string, List<TypeSlotModel>>(StringComparer.Ordinal);

            int globalIndex = 0;
            for (int s = 0; s < template.Slots.Count; s++)
            {
                SlotModel slot = template.Slots[s];
                int count = EvaluateCountExpression(slot.CountExpression, arity);
                if (count < 0)
                {
                    rendered = string.Empty;
                    return false;
                }

                var family = new List<TypeSlotModel>(count);
                for (int i = 1; i <= count; i++)
                {
                    int zeroIndex = i - 1;
                    string typeName = ApplyPattern(slot.TypePattern, i, zeroIndex);
                    string paramTypeName = ApplyTypeTemplate(slot.ParamTypePattern, typeName);
                    var typeSlot = new TypeSlotModel(
                        slot.Name,
                        typeName,
                        paramTypeName,
                        ApplyPattern(slot.ParamPattern, i, zeroIndex),
                        ApplyPattern(slot.LocalPattern, i, zeroIndex),
                        slot.Constraint,
                        zeroIndex,
                        globalIndex);
                    family.Add(typeSlot);
                    allSlots.Add(typeSlot);
                    globalIndex++;
                }

                slotsByName[slot.Name] = family;
            }

            rendered = template.Body;

            rendered = EachTypesRegex.Replace(rendered, m =>
            {
                var slots = ResolveSlots(m.Groups["slot"].Value, allSlots, slotsByName);
                if (slots.Count == 0)
                {
                    return string.Empty;
                }

                return RenderSlots(slots, m.Groups["inner"].Value, string.Empty);
            });

            rendered = JoinBlockRegex.Replace(rendered, m =>
            {
                var slots = ResolveSlots(m.Groups["slot"].Value, allSlots, slotsByName);
                if (slots.Count == 0)
                {
                    return string.Empty;
                }

                string rawSeparator = m.Groups["separator"].Value;
                string separator = Regex.Unescape(rawSeparator.Substring(1, rawSeparator.Length - 2));
                return RenderSlots(slots, m.Groups["inner"].Value, separator);
            });

            rendered = JoinMacroRegex.Replace(rendered, m =>
            {
                var slots = ResolveSlots(m.Groups["slot"].Value, allSlots, slotsByName);
                if (slots.Count == 0)
                {
                    return string.Empty;
                }

                return m.Groups["kind"].Value.Equals("ARGS", StringComparison.Ordinal)
                    ? BuildArgs(slots)
                    : BuildRefArgs(slots);
            });

            rendered = rendered.Replace("{{TYPE_COUNT}}", allSlots.Count.ToString());
            rendered = rendered.Replace("{{GENERICS}}", BuildGenerics(allSlots));
            rendered = rendered.Replace("{{PARAMS}}", BuildParams(allSlots));
            rendered = rendered.Replace("{{WHERE_BLOCK}}", BuildWhereBlock(allSlots));
            rendered = rendered.Replace("{{TYPE_ARGS}}", BuildArgs(allSlots));
            rendered = rendered.Replace("{{TYPE_ARGS_REF}}", BuildRefArgs(allSlots));
            rendered = rendered.Replace("{{PARAM_ARGS}}", BuildParamArgs(allSlots));

            rendered = rendered.Trim();
            return rendered.Length > 0;
        }

        static List<TypeSlotModel> ResolveSlots(string slotName, List<TypeSlotModel> allSlots, Dictionary<string, List<TypeSlotModel>> slotsByName)
        {
            if (string.IsNullOrWhiteSpace(slotName))
            {
                return allSlots;
            }

            if (slotsByName.TryGetValue(slotName, out var slots))
            {
                return slots;
            }

            return new List<TypeSlotModel>();
        }

        static string RenderSlots(List<TypeSlotModel> slots, string template, string separator)
        {
            var rendered = new string[slots.Count];
            for (int i = 0; i < slots.Count; i++)
            {
                rendered[i] = RenderSlot(template, slots[i]);
            }

            return string.Join(separator, rendered);
        }

        static string RenderSlot(string template, TypeSlotModel slot)
        {
            return template
                .Replace("{{TYPE}}", slot.TypeName)
                .Replace("{{TYPE_NAME}}", slot.TypeName)
                .Replace("{{PARAM_NAME}}", slot.ParamName)
                .Replace("{{LOCAL_NAME}}", slot.LocalName)
                .Replace("{{INDEX}}", slot.GroupIndex.ToString())
                .Replace("{{GLOBAL_INDEX}}", slot.GlobalIndex.ToString())
                .Replace("{{GROUP_NAME}}", slot.GroupName);
        }

        static int EvaluateCountExpression(string expression, int arity)
        {
            if (string.IsNullOrWhiteSpace(expression))
            {
                return arity;
            }

            string value = expression.Trim();
            if (value.Equals("arity", StringComparison.Ordinal) || value.Equals("n", StringComparison.Ordinal))
            {
                return arity;
            }

            if (int.TryParse(value, out int absolute))
            {
                return absolute;
            }

            Match match = ArityExpressionRegex.Match(value);
            if (!match.Success)
            {
                return arity;
            }

            if (!int.TryParse(match.Groups["value"].Value, out int delta))
            {
                return arity;
            }

            return match.Groups["op"].Value == "+" ? arity + delta : arity - delta;
        }

        static string ApplyPattern(string pattern, int oneIndex, int zeroIndex)
        {
            return pattern
                .Replace("{n}", oneIndex.ToString())
                .Replace("{i}", zeroIndex.ToString())
                .Replace("{i0}", zeroIndex.ToString());
        }

        static string ApplyTypeTemplate(string pattern, string typeName)
        {
            return pattern.Replace("{{TYPE_NAME}}", typeName);
        }

        static string BuildGenerics(List<TypeSlotModel> slots)
        {
            if (slots.Count == 0) return string.Empty;

            var items = new string[slots.Count];
            for (int i = 0; i < slots.Count; i++)
            {
                items[i] = slots[i].TypeName;
            }

            return string.Join(", ", items);
        }

        static string BuildParamArgs(List<TypeSlotModel> slots)
        {
            if (slots.Count == 0) return string.Empty;

            var items = new string[slots.Count];
            for (int i = 0; i < slots.Count; i++)
            {
                items[i] = slots[i].ParamName;
            }

            return string.Join(", ", items);
        }

        static string BuildArgs(List<TypeSlotModel> slots)
        {
            if (slots.Count == 0) return string.Empty;

            var items = new string[slots.Count];
            for (int i = 0; i < slots.Count; i++)
            {
                items[i] = slots[i].LocalName;
            }

            return string.Join(", ", items);
        }

        static string BuildRefArgs(List<TypeSlotModel> slots)
        {
            if (slots.Count == 0) return string.Empty;

            var items = new string[slots.Count];
            for (int i = 0; i < slots.Count; i++)
            {
                items[i] = "ref " + slots[i].LocalName;
            }

            return string.Join(", ", items);
        }

        static string BuildParams(List<TypeSlotModel> slots)
        {
            if (slots.Count == 0) return string.Empty;

            var items = new string[slots.Count];
            for (int i = 0; i < slots.Count; i++)
            {
                items[i] = slots[i].ParamTypeName + " " + slots[i].ParamName;
            }

            return string.Join(", ", items);
        }

        static string BuildWhereBlock(List<TypeSlotModel> slots)
        {
            var constrained = new List<TypeSlotModel>(slots.Count);
            for (int i = 0; i < slots.Count; i++)
            {
                if (!string.IsNullOrWhiteSpace(slots[i].Constraint))
                {
                    constrained.Add(slots[i]);
                }
            }

            if (constrained.Count == 0) return string.Empty;

            var sb = new StringBuilder();
            for (int i = 0; i < constrained.Count; i++)
            {
                if (i > 0) sb.AppendLine();
                sb.Append("where ").Append(constrained[i].TypeName).Append(" : ").Append(constrained[i].Constraint);
            }

            return sb.ToString();
        }

        static string[] ParseList(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return Array.Empty<string>();
            }

            string[] raw = value.Split(',');
            var items = new List<string>(raw.Length);
            for (int i = 0; i < raw.Length; i++)
            {
                string item = raw[i].Trim();
                if (item.Length > 0)
                {
                    items.Add(item);
                }
            }

            return items.ToArray();
        }

        static string StripCommentPrefix(string input)
        {
            List<string> lines = SplitLines(input);
            for (int i = 0; i < lines.Count; i++)
            {
                string line = lines[i];
                int starIndex = line.IndexOf('*');
                if (starIndex >= 0)
                {
                    string afterStar = line.Substring(starIndex + 1);
                    if (afterStar.StartsWith(" ", StringComparison.Ordinal))
                    {
                        afterStar = afterStar.Substring(1);
                    }

                    lines[i] = afterStar;
                }
            }

            return string.Join("\n", lines);
        }

        static List<string> SplitLines(string text)
        {
            return new List<string>(text.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n'));
        }

        readonly struct TemplateModel
        {
            public readonly string TemplateName;
            public readonly string HintName;
            public readonly string NamespaceName;
            public readonly string ContainerDeclaration;
            public readonly string[] Usings;
            public readonly string Body;
            public readonly int MaxArity;
            public readonly List<SlotModel> Slots;

            public TemplateModel(string templateName, string hintName, string namespaceName, string containerDeclaration, string[] usings, string body, int maxArity, List<SlotModel> slots)
            {
                TemplateName = templateName;
                HintName = hintName;
                NamespaceName = namespaceName;
                ContainerDeclaration = containerDeclaration;
                Usings = usings;
                Body = body;
                MaxArity = maxArity;
                Slots = slots;
            }
        }

        readonly struct SlotModel
        {
            public readonly string Name;
            public readonly string CountExpression;
            public readonly string Constraint;
            public readonly string TypePattern;
            public readonly string ParamPattern;
            public readonly string LocalPattern;
            public readonly string ParamTypePattern;

            public SlotModel(string name, string countExpression, string constraint, string typePattern, string paramPattern, string localPattern, string paramTypePattern)
            {
                Name = name;
                CountExpression = countExpression;
                Constraint = constraint;
                TypePattern = typePattern;
                ParamPattern = paramPattern;
                LocalPattern = localPattern;
                ParamTypePattern = paramTypePattern;
            }
        }

        struct SlotBuilder
        {
            public string Name;
            public string CountExpression;
            public string Constraint;
            public string TypePattern;
            public string ParamPattern;
            public string LocalPattern;
            public string ParamTypePattern;

            public SlotBuilder(string name)
            {
                Name = name;
                CountExpression = string.Empty;
                Constraint = string.Empty;
                TypePattern = string.Empty;
                ParamPattern = string.Empty;
                LocalPattern = string.Empty;
                ParamTypePattern = string.Empty;
            }

            public void Set(string key, string value)
            {
                switch (key)
                {
                    case "count":
                        CountExpression = value;
                        break;
                    case "constraint":
                        Constraint = value;
                        break;
                    case "type":
                        TypePattern = value;
                        break;
                    case "param":
                        ParamPattern = value;
                        break;
                    case "local":
                        LocalPattern = value;
                        break;
                    case "paramType":
                        ParamTypePattern = value;
                        break;
                }
            }

            public SlotModel Build()
            {
                string defaultType = Name + "{n}";
                string defaultParam = Name.ToLowerInvariant() + "{n}";
                return new SlotModel(
                    Name,
                    CountExpression.Length == 0 ? "arity" : CountExpression,
                    Constraint,
                    TypePattern.Length == 0 ? defaultType : TypePattern,
                    ParamPattern.Length == 0 ? defaultParam : ParamPattern,
                    LocalPattern.Length == 0 ? "v{n}" : LocalPattern,
                    ParamTypePattern.Length == 0 ? "{{TYPE_NAME}}" : ParamTypePattern);
            }
        }

        readonly struct TypeSlotModel
        {
            public readonly string GroupName;
            public readonly string TypeName;
            public readonly string ParamTypeName;
            public readonly string ParamName;
            public readonly string LocalName;
            public readonly string Constraint;
            public readonly int GroupIndex;
            public readonly int GlobalIndex;

            public TypeSlotModel(string groupName, string typeName, string paramTypeName, string paramName, string localName, string constraint, int groupIndex, int globalIndex)
            {
                GroupName = groupName;
                TypeName = typeName;
                ParamTypeName = paramTypeName;
                ParamName = paramName;
                LocalName = localName;
                Constraint = constraint;
                GroupIndex = groupIndex;
                GlobalIndex = globalIndex;
            }
        }
    }
}
