using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Glai.ECS.SourceGen
{
    [Generator]
    public class SystemGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var systemResults = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is StructDeclarationSyntax,
                    transform: static (ctx, ct) => ExtractSystemModel(ctx, ct));

            var systemModels = systemResults
                .Where(static r => r.Model != null)
                .Select(static (r, _) => r.Model!.Value);

            var allSystemModels = systemModels.Collect();

            context.RegisterSourceOutput(systemResults, static (spc, result) => Emit(spc, result));
            context.RegisterSourceOutput(allSystemModels, static (spc, models) => EmitNamespaceApis(spc, models));
        }

        static SystemModelResult ExtractSystemModel(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            var structSyntax = (StructDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(structSyntax, ct);
            if (symbol is not INamedTypeSymbol namedType)
                return default;

            if (namedType.ContainingType != null)
                return default;

            if (!TryGetQueryExecution(namedType, out QueryExecutionMode executionMode, out DiagnosticInfo? queryDiagnostic))
                return new SystemModelResult(null, queryDiagnostic);

            if (!TryResolveExecuteSignature(namedType, out var accesses, out bool injectEntityId, out DiagnosticInfo? executeDiagnostic))
                return new SystemModelResult(null, executeDiagnostic);

            var namespaceSymbol = namedType.ContainingNamespace;
            string? namespaceName = (namespaceSymbol != null && !namespaceSymbol.IsGlobalNamespace)
                ? namespaceSymbol.ToDisplayString()
                : null;

            return new SystemModelResult(new SystemModel(
                namedType.Name,
                namedType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                namespaceName,
                accesses,
                executionMode,
                HasNonBurstQueryAttribute(namedType),
                injectEntityId), null);
        }

        static void Emit(SourceProductionContext spc, SystemModelResult result)
        {
            if (result.Diagnostic is DiagnosticInfo diagnostic)
                spc.ReportDiagnostic(Diagnostic.Create(diagnostic.Descriptor, diagnostic.Location, diagnostic.MessageArgs));

            if (result.Model is SystemModel model)
                EmitModel(spc, model);
        }

        static void EmitModel(SourceProductionContext spc, SystemModel model)
        {
            var sb = new StringBuilder(8192);
            int arity = model.Accesses.Length;
            string indent = model.Namespace != null ? "    " : string.Empty;

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            if (!model.IsNonBurst)
                sb.AppendLine("using Unity.Burst;");
            sb.AppendLine("using Unity.Collections.LowLevel.Unsafe;");
            sb.AppendLine("using Unity.Jobs;");
            sb.AppendLine("using Glai.Allocator;");
            sb.AppendLine("using Glai.ECS;");
            sb.AppendLine("using Glai.ECS.Core;");
            sb.AppendLine("using Glai.Core;");
            sb.AppendLine();

            if (model.Namespace != null)
            {
                sb.AppendLine($"namespace {model.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"{indent}[StructLayout(LayoutKind.Sequential)]");
            sb.AppendLine($"{indent}internal unsafe struct {model.SystemName}__ChunkData");
            sb.AppendLine($"{indent}{{");
            for (int i = 0; i < arity; i++)
            {
                sb.AppendLine($"{indent}    public byte* c{i};");
                if (model.Accesses[i].Kind == AccessKind.Buffer)
                    sb.AppendLine($"{indent}    public int s{i};");
            }
            if (model.InjectEntityId)
                sb.AppendLine($"{indent}    public int* entityIds;");
            sb.AppendLine($"{indent}    public int entityCount;");
            if (model.ExecutionMode == QueryExecutionMode.EntityParallel)
                sb.AppendLine($"{indent}    public int entityStart;");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();

            if (!model.IsNonBurst)
            {
                EmitBurstHelpers(sb, model, indent);

                switch (model.ExecutionMode)
                {
                    case QueryExecutionMode.Async:
                        EmitAsyncJob(sb, model, indent);
                        break;
                    case QueryExecutionMode.ChunkParallel:
                        EmitChunkParallelJob(sb, model, indent);
                        break;
                    case QueryExecutionMode.EntityParallel:
                        EmitEntityParallelJob(sb, model, indent);
                        break;
                }
            }

            EmitDispatch(sb, model, indent);
            EmitExtensions(sb, model, indent);

            if (model.Namespace != null)
                sb.AppendLine("}");

            spc.AddSource($"{model.SystemName}__Generated.g.cs", sb.ToString());
        }

        static void EmitBurstHelpers(StringBuilder sb, SystemModel model, string indent)
        {
            sb.AppendLine($"{indent}internal unsafe static class {model.SystemName}__Burst");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    [BurstCompile]");
            sb.AppendLine($"{indent}    internal static void ExecuteChunk(ref {model.SystemFullyQualifiedName} system, ref {model.SystemName}__ChunkData data)");
            sb.AppendLine($"{indent}    {{");
            EmitAccessLocals(sb, model, indent, "data", false);
            sb.AppendLine($"{indent}        int count = data.entityCount;");
            sb.AppendLine($"{indent}        for (int i = 0; i < count; i++)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            system.Execute({BuildExecuteArgs(model.Accesses, "i", model.InjectEntityId, "data.entityIds[i]")});");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            sb.AppendLine($"{indent}    [BurstCompile]");
            sb.AppendLine($"{indent}    internal static void ExecuteEntity(ref {model.SystemFullyQualifiedName} system, ref {model.SystemName}__ChunkData data, int entityIndex)");
            sb.AppendLine($"{indent}    {{");
            EmitAccessLocals(sb, model, indent, "data", false);
            sb.AppendLine($"{indent}        system.Execute({BuildExecuteArgs(model.Accesses, "entityIndex", model.InjectEntityId, "data.entityIds[entityIndex]")});");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }

        static void EmitAsyncJob(StringBuilder sb, SystemModel model, string indent)
        {
            sb.AppendLine($"{indent}[BurstCompile]");
            sb.AppendLine($"{indent}internal unsafe struct {model.SystemName}__AsyncJob : IJob");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public {model.SystemFullyQualifiedName} System;");
            sb.AppendLine($"{indent}    [NativeDisableUnsafePtrRestriction] public {model.SystemName}__ChunkData* Chunks;");
            sb.AppendLine($"{indent}    public int ChunkCount;");
            sb.AppendLine();
            sb.AppendLine($"{indent}    public void Execute()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        for (int chunkIndex = 0; chunkIndex < ChunkCount; chunkIndex++)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            {model.SystemName}__Burst.ExecuteChunk(ref System, ref Chunks[chunkIndex]);");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }

        static void EmitChunkParallelJob(StringBuilder sb, SystemModel model, string indent)
        {
            sb.AppendLine($"{indent}[BurstCompile]");
            sb.AppendLine($"{indent}internal unsafe struct {model.SystemName}__ChunkParallelJob : IJobParallelFor");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public {model.SystemFullyQualifiedName} System;");
            sb.AppendLine($"{indent}    [NativeDisableUnsafePtrRestriction] public {model.SystemName}__ChunkData* Chunks;");
            sb.AppendLine();
            sb.AppendLine($"{indent}    public void Execute(int index)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        {model.SystemName}__Burst.ExecuteChunk(ref System, ref Chunks[index]);");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }

        static void EmitEntityParallelJob(StringBuilder sb, SystemModel model, string indent)
        {
            sb.AppendLine($"{indent}[BurstCompile]");
            sb.AppendLine($"{indent}internal unsafe struct {model.SystemName}__EntityParallelJob : IJobParallelFor");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public {model.SystemFullyQualifiedName} System;");
            sb.AppendLine($"{indent}    [NativeDisableUnsafePtrRestriction] public {model.SystemName}__ChunkData* Chunks;");
            sb.AppendLine($"{indent}    public int ChunkCount;");
            sb.AppendLine();
            sb.AppendLine($"{indent}    public void Execute(int index)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        int low = 0;");
            sb.AppendLine($"{indent}        int high = ChunkCount - 1;");
            sb.AppendLine($"{indent}        while (low <= high)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            int mid = (low + high) >> 1;");
            sb.AppendLine($"{indent}            ref var data = ref Chunks[mid];");
            sb.AppendLine($"{indent}            int end = data.entityStart + data.entityCount;");
            sb.AppendLine($"{indent}            if (index < data.entityStart)");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                high = mid - 1;");
            sb.AppendLine($"{indent}                continue;");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}            if (index >= end)");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                low = mid + 1;");
            sb.AppendLine($"{indent}                continue;");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}            {model.SystemName}__Burst.ExecuteEntity(ref System, ref data, index - data.entityStart);");
            sb.AppendLine($"{indent}            return;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }

        static void EmitDispatch(StringBuilder sb, SystemModel model, string indent)
        {
            sb.AppendLine($"{indent}internal unsafe struct {model.SystemName}__Dispatch : global::Glai.ECS.IQueryJobDispatch");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public {model.SystemFullyQualifiedName} System;");
            sb.AppendLine();
            for (int i = 0; i < model.Accesses.Length; i++)
                sb.AppendLine($"{indent}    private int _s{i};");
            sb.AppendLine();
            sb.AppendLine($"{indent}    private {model.SystemName}__ChunkData* _chunkDataPtr;");
            if (model.ExecutionMode == QueryExecutionMode.EntityParallel)
                sb.AppendLine($"{indent}    private int _totalEntityCount;");
            sb.AppendLine();
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    public void Prepare(global::Glai.Allocator.MemoryStateHandle arenaHandle, global::Glai.ECS.Core.ECSMemoryState memoryState, int maxChunks)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var allocator = memoryState.GetAllocator(arenaHandle);");
            sb.AppendLine($"{indent}        var arrayHandle = allocator.AllocateArray<{model.SystemName}__ChunkData>(maxChunks);");
            sb.AppendLine($"{indent}        var chunkDataSpan = allocator.GetArray<{model.SystemName}__ChunkData>(arrayHandle);");
            sb.AppendLine($"{indent}        fixed ({model.SystemName}__ChunkData* chunkDataPtr = chunkDataSpan)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            _chunkDataPtr = chunkDataPtr;");
            sb.AppendLine($"{indent}        }}");
            if (model.ExecutionMode == QueryExecutionMode.EntityParallel)
                sb.AppendLine($"{indent}        _totalEntityCount = 0;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    public bool PrepareArchetype(ref global::Glai.ECS.Core.Archetype archetype)");
            sb.AppendLine($"{indent}    {{");
            for (int i = 0; i < model.Accesses.Length; i++)
                sb.AppendLine($"{indent}        _s{i} = archetype.GetComponentStorageIndex(global::Glai.Core.TypeId<{model.Accesses[i].InnerFullName}>.Id);");
            string failCheck = string.Join(" || ", Enumerable.Range(0, model.Accesses.Length).Select(i => $"_s{i} == -1"));
            sb.AppendLine($"{indent}        if ({failCheck}) return false;");
            sb.AppendLine($"{indent}        return true;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    public void CollectChunk(ref global::Glai.ECS.Core.Chunk chunk, int chunkIndex)");
            sb.AppendLine($"{indent}    {{");
            for (int i = 0; i < model.Accesses.Length; i++)
            {
                sb.AppendLine($"{indent}        _chunkDataPtr[chunkIndex].c{i} = chunk.GetComponentPtr(_s{i});");
                if (model.Accesses[i].Kind == AccessKind.Buffer)
                    sb.AppendLine($"{indent}        _chunkDataPtr[chunkIndex].s{i} = chunk.GetComponentSize(_s{i});");
            }
            if (model.InjectEntityId)
                sb.AppendLine($"{indent}        _chunkDataPtr[chunkIndex].entityIds = chunk.GetEntityIds();");
            sb.AppendLine($"{indent}        _chunkDataPtr[chunkIndex].entityCount = chunk.EntityCount;");
            if (model.ExecutionMode == QueryExecutionMode.EntityParallel)
            {
                sb.AppendLine($"{indent}        _chunkDataPtr[chunkIndex].entityStart = _totalEntityCount;");
                sb.AppendLine($"{indent}        _totalEntityCount += chunk.EntityCount;");
            }
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    public global::Unity.Jobs.JobHandle ScheduleParallel(int chunkCount)");
            sb.AppendLine($"{indent}    {{");
            if (model.IsNonBurst && model.ExecutionMode != QueryExecutionMode.MainThread)
            {
                sb.AppendLine($"{indent}        throw new global::System.InvalidOperationException(\"[NonBurstQuery] is only supported with QueryExecution.MainThread.\");");
            }
            else if (model.IsNonBurst)
            {
                sb.AppendLine($"{indent}        throw new global::System.InvalidOperationException(\"[NonBurstQuery] jobs must be run with RunNonBurst.\");");
            }
            else
            {
                switch (model.ExecutionMode)
                {
                    case QueryExecutionMode.MainThread:
                        sb.AppendLine($"{indent}        var system = System;");
                        sb.AppendLine($"{indent}        for (int chunkIndex = 0; chunkIndex < chunkCount; chunkIndex++)");
                        sb.AppendLine($"{indent}        {{");
                        sb.AppendLine($"{indent}            {model.SystemName}__Burst.ExecuteChunk(ref system, ref _chunkDataPtr[chunkIndex]);");
                        sb.AppendLine($"{indent}        }}");
                        sb.AppendLine($"{indent}        System = system;");
                        sb.AppendLine($"{indent}        return default;");
                        break;
                    case QueryExecutionMode.Async:
                        sb.AppendLine($"{indent}        var job = new {model.SystemName}__AsyncJob");
                        sb.AppendLine($"{indent}        {{");
                        sb.AppendLine($"{indent}            System = this.System,");
                        sb.AppendLine($"{indent}            Chunks = _chunkDataPtr,");
                        sb.AppendLine($"{indent}            ChunkCount = chunkCount,");
                        sb.AppendLine($"{indent}        }};");
                        sb.AppendLine($"{indent}        return job.Schedule();");
                        break;
                    case QueryExecutionMode.ChunkParallel:
                        sb.AppendLine($"{indent}        var job = new {model.SystemName}__ChunkParallelJob");
                        sb.AppendLine($"{indent}        {{");
                        sb.AppendLine($"{indent}            System = this.System,");
                        sb.AppendLine($"{indent}            Chunks = _chunkDataPtr,");
                        sb.AppendLine($"{indent}        }};");
                        sb.AppendLine($"{indent}        return job.Schedule(chunkCount, 1);");
                        break;
                    case QueryExecutionMode.EntityParallel:
                        sb.AppendLine($"{indent}        var job = new {model.SystemName}__EntityParallelJob");
                        sb.AppendLine($"{indent}        {{");
                        sb.AppendLine($"{indent}            System = this.System,");
                        sb.AppendLine($"{indent}            Chunks = _chunkDataPtr,");
                        sb.AppendLine($"{indent}            ChunkCount = chunkCount,");
                        sb.AppendLine($"{indent}        }};");
                        sb.AppendLine($"{indent}        return job.Schedule(_totalEntityCount, 1);");
                        break;
                }
            }
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    public void RunNonBurst(int chunkCount)");
            sb.AppendLine($"{indent}    {{");
            if (!model.IsNonBurst)
            {
                sb.AppendLine($"{indent}        throw new global::System.InvalidOperationException(\"[{model.ExecutionModeName}] jobs must be run with Run.\");");
            }
            else if (model.ExecutionMode != QueryExecutionMode.MainThread)
            {
                sb.AppendLine($"{indent}        throw new global::System.InvalidOperationException(\"[NonBurstQuery] is only supported with QueryExecution.MainThread.\");");
            }
            else
            {
                sb.AppendLine($"{indent}        var system = System;");
                sb.AppendLine($"{indent}        for (int chunkIndex = 0; chunkIndex < chunkCount; chunkIndex++)");
                sb.AppendLine($"{indent}        {{");
                EmitAccessLocals(sb, model, indent, $"_chunkDataPtr[chunkIndex]", true);
                sb.AppendLine($"{indent}            int count = _chunkDataPtr[chunkIndex].entityCount;");
                sb.AppendLine($"{indent}            for (int entityIndex = 0; entityIndex < count; entityIndex++)");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                system.Execute({BuildExecuteArgs(model.Accesses, "entityIndex", model.InjectEntityId, "entityIds[entityIndex]")});");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        System = system;");
            }
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }

        static void EmitExtensions(StringBuilder sb, SystemModel model, string indent)
        {
            sb.AppendLine($"{indent}internal static class {model.SystemName}__Extensions");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public static global::Glai.ECS.QueryJobHandle Run(this global::Glai.ECS.EntityManager em, global::Glai.ECS.QueryBuilder query, ref {model.SystemFullyQualifiedName} system)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var dispatch = new {model.SystemName}__Dispatch {{ System = system }};");
            sb.AppendLine($"{indent}        var handle = em.Run(query, ref dispatch);");
            sb.AppendLine($"{indent}        system = dispatch.System;");
            sb.AppendLine($"{indent}        return handle;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    public static global::Glai.ECS.QueryJobHandle RunNonBurst(this global::Glai.ECS.EntityManager em, global::Glai.ECS.QueryBuilder query, ref {model.SystemFullyQualifiedName} system)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var dispatch = new {model.SystemName}__Dispatch {{ System = system }};");
            sb.AppendLine($"{indent}        var handle = em.RunNonBurst(query, ref dispatch);");
            sb.AppendLine($"{indent}        system = dispatch.System;");
            sb.AppendLine($"{indent}        return handle;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
        }

        static void EmitNamespaceApis(SourceProductionContext spc, ImmutableArray<SystemModel> models)
        {
            foreach (var group in models.GroupBy(static m => m.Namespace, System.StringComparer.Ordinal))
            {
                var sb = new StringBuilder(4096);
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("#pragma warning disable");
                sb.AppendLine("using System.Runtime.CompilerServices;");
                sb.AppendLine();

                if (group.Key != null)
                {
                    sb.AppendLine($"namespace {group.Key}");
                    sb.AppendLine("{");
                }

                string indent = group.Key != null ? "    " : string.Empty;
                sb.AppendLine($"{indent}internal static partial class ECSAPI");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"{indent}    public static global::Glai.ECS.Entity CreateEntity(int archetypeIndex) => global::Glai.ECS.ECSAPI.CreateEntity(archetypeIndex);");
                sb.AppendLine();
                sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"{indent}    public static void DestroyEntity(global::Glai.ECS.Entity entity) => global::Glai.ECS.ECSAPI.DestroyEntity(entity);");
                sb.AppendLine();
                sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"{indent}    public static bool IsValid(global::Glai.ECS.Entity entity) => global::Glai.ECS.ECSAPI.IsValid(entity);");
                sb.AppendLine();
                sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"{indent}    public static T GetComponent<T>(global::Glai.ECS.Entity entity) where T : unmanaged, global::Glai.ECS.IComponent");
                sb.AppendLine($"{indent}        => global::Glai.ECS.ECSAPI.GetComponent<T>(entity);");
                sb.AppendLine();
                sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"{indent}    public static ref T GetComponentRef<T>(global::Glai.ECS.Entity entity) where T : unmanaged, global::Glai.ECS.IComponent");
                sb.AppendLine($"{indent}        => ref global::Glai.ECS.ECSAPI.GetComponentRef<T>(entity);");
                sb.AppendLine();
                sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"{indent}    public static int CreateArchetype(global::System.ReadOnlySpan<global::Glai.ECS.ArchetypeType> types) => global::Glai.ECS.ECSAPI.CreateArchetype(types);");
                sb.AppendLine();
                sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"{indent}    public static global::Glai.ECS.QueryBuilder Query() => global::Glai.ECS.ECSAPI.Query();");
                sb.AppendLine();
                sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"{indent}    public static global::Glai.ECS.QueryJobHandle Run<TDispatch>(global::Glai.ECS.QueryBuilder query, ref TDispatch dispatch)");
                sb.AppendLine($"{indent}        where TDispatch : struct, global::Glai.ECS.IQueryJobDispatch");
                sb.AppendLine($"{indent}        => global::Glai.ECS.ECSAPI.Run(query, ref dispatch);");
                sb.AppendLine();
                sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"{indent}    public static global::Glai.ECS.QueryJobHandle RunNonBurst<TDispatch>(global::Glai.ECS.QueryBuilder query, ref TDispatch dispatch)");
                sb.AppendLine($"{indent}        where TDispatch : struct, global::Glai.ECS.IQueryJobDispatch");
                sb.AppendLine($"{indent}        => global::Glai.ECS.ECSAPI.RunNonBurst(query, ref dispatch);");

                foreach (SystemModel model in group.OrderBy(static m => m.SystemFullyQualifiedName, System.StringComparer.Ordinal))
                {
                    sb.AppendLine();
                    sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                    sb.AppendLine($"{indent}    internal static global::Glai.ECS.QueryJobHandle Run(global::Glai.ECS.QueryBuilder query, ref {model.SystemFullyQualifiedName} system)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        var manager = (global::Glai.ECS.EntityManager)global::Glai.ECS.Core.IEntityManager.Instance;");
                    sb.AppendLine($"{indent}        var dispatch = new {model.SystemName}__Dispatch {{ System = system }};");
                    sb.AppendLine($"{indent}        var handle = manager.Run(query, ref dispatch);");
                    sb.AppendLine($"{indent}        system = dispatch.System;");
                    sb.AppendLine($"{indent}        return handle;");
                    sb.AppendLine($"{indent}    }}");
                    sb.AppendLine();
                    sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                    sb.AppendLine($"{indent}    internal static global::Glai.ECS.QueryJobHandle RunNonBurst(global::Glai.ECS.QueryBuilder query, ref {model.SystemFullyQualifiedName} system)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        var manager = (global::Glai.ECS.EntityManager)global::Glai.ECS.Core.IEntityManager.Instance;");
                    sb.AppendLine($"{indent}        var dispatch = new {model.SystemName}__Dispatch {{ System = system }};");
                    sb.AppendLine($"{indent}        var handle = manager.RunNonBurst(query, ref dispatch);");
                    sb.AppendLine($"{indent}        system = dispatch.System;");
                    sb.AppendLine($"{indent}        return handle;");
                    sb.AppendLine($"{indent}    }}");
                }

                sb.AppendLine($"{indent}}}");

                if (group.Key != null)
                    sb.AppendLine("}");

                string hintName = (group.Key ?? "Global").Replace('.', '_') + "__ECSAPI.g.cs";
                spc.AddSource(hintName, sb.ToString());
            }
        }

        static void EmitAccessLocals(StringBuilder sb, SystemModel model, string indent, string dataExpr, bool includeEntityIdsLocal)
        {
            for (int i = 0; i < model.Accesses.Length; i++)
            {
                if (model.Accesses[i].Kind == AccessKind.Ref)
                {
                    sb.AppendLine($"{indent}        {model.Accesses[i].InnerFullName}* p{i} = ({model.Accesses[i].InnerFullName}*){dataExpr}.c{i};");
                }
                else
                {
                    sb.AppendLine($"{indent}        byte* p{i} = {dataExpr}.c{i};");
                    sb.AppendLine($"{indent}        int s{i} = {dataExpr}.s{i};");
                }
            }

            if (model.InjectEntityId && includeEntityIdsLocal)
                sb.AppendLine($"{indent}        int* entityIds = {dataExpr}.entityIds;");
        }

        static bool TryResolveExecuteSignature(INamedTypeSymbol namedType, out ImmutableArray<AccessModel> accesses, out bool injectEntityId, out DiagnosticInfo? diagnostic)
        {
            accesses = default;
            injectEntityId = false;
            diagnostic = null;

            var validMethods = ImmutableArray.CreateBuilder<ExecuteSignatureModel>();
            var executeMethods = namedType.GetMembers("Execute").OfType<IMethodSymbol>();
            foreach (IMethodSymbol method in executeMethods)
            {
                if (method.MethodKind != MethodKind.Ordinary || method.IsStatic || !method.ReturnsVoid)
                    continue;

                if (TryCreateExecuteSignature(method, out ExecuteSignatureModel signature))
                    validMethods.Add(signature);
            }

            if (validMethods.Count == 0)
            {
                diagnostic = new DiagnosticInfo(
                    InvalidExecuteSignature,
                    namedType.Locations.FirstOrDefault(),
                    namedType.Name,
                    "Execute(Ref<T>/Buffer<T>...) or Execute(int entityId, Ref<T>/Buffer<T>...) with 1 to 7 bindable parameters");
                return false;
            }

            if (validMethods.Count > 1)
            {
                diagnostic = new DiagnosticInfo(
                    AmbiguousExecuteSignature,
                    namedType.Locations.FirstOrDefault(),
                    namedType.Name);
                return false;
            }

            accesses = validMethods[0].Accesses;
            injectEntityId = validMethods[0].InjectEntityId;
            return true;
        }

        static bool TryCreateExecuteSignature(IMethodSymbol method, out ExecuteSignatureModel signature)
        {
            signature = default;
            bool injectEntityId = false;
            int offset = 0;

            if (method.Parameters.Length == 0)
                return false;

            if (method.Parameters[0].Type.SpecialType == SpecialType.System_Int32)
            {
                injectEntityId = true;
                offset = 1;
            }

            int bindableParameterCount = method.Parameters.Length - offset;
            if (bindableParameterCount <= 0 || bindableParameterCount > 7)
                return false;

            var accesses = ImmutableArray.CreateBuilder<AccessModel>(bindableParameterCount);
            for (int i = offset; i < method.Parameters.Length; i++)
            {
                if (!TryCreateAccessModel(method.Parameters[i].Type, out AccessModel access))
                    return false;

                accesses.Add(access);
            }

            signature = new ExecuteSignatureModel(accesses.ToImmutable(), injectEntityId);
            return true;
        }

        static bool TryCreateAccessModel(ITypeSymbol parameterType, out AccessModel access)
        {
            access = default;
            if (parameterType is not INamedTypeSymbol accessType || accessType.TypeArguments.Length != 1)
                return false;

            var ns = accessType.OriginalDefinition.ContainingNamespace?.ToDisplayString();
            var metadataName = accessType.OriginalDefinition.MetadataName;
            AccessKind kind;
            if (ns == "Glai.ECS" && metadataName == "Ref`1")
            {
                kind = AccessKind.Ref;
            }
            else if (ns == "Glai.ECS" && metadataName == "Buffer`1")
            {
                kind = AccessKind.Buffer;
            }
            else
            {
                return false;
            }

            access = new AccessModel(
                kind,
                accessType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                accessType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            return true;
        }

        static string BuildExecuteArgs(ImmutableArray<AccessModel> accesses, string indexExpr, bool injectEntityId, string entityIdExpr)
        {
            var args = new StringBuilder();
            if (injectEntityId)
                args.Append(entityIdExpr);

            for (int i = 0; i < accesses.Length; i++)
            {
                if (args.Length > 0)
                    args.Append(", ");

                var access = accesses[i];
                if (access.Kind == AccessKind.Ref)
                {
                    args.Append($"new global::Glai.ECS.Ref<{access.InnerFullName}>(&p{i}[{indexExpr}])");
                }
                else
                {
                    args.Append($"new global::Glai.ECS.Buffer<{access.InnerFullName}>(p{i} + ({indexExpr}) * s{i}, global::Glai.ECS.Core.BufferTypeInfo<{access.InnerFullName}>.GetCapacity(s{i}))");
                }
            }

            return args.ToString();
        }

        static bool TryGetQueryExecution(INamedTypeSymbol namedType, out QueryExecutionMode executionMode, out DiagnosticInfo? diagnostic)
        {
            executionMode = default;
            diagnostic = null;

            foreach (AttributeData attribute in namedType.GetAttributes())
            {
                if (attribute.AttributeClass?.ContainingNamespace?.ToDisplayString() != "Glai.ECS")
                    continue;

                if (attribute.AttributeClass.MetadataName != "QueryJobAttribute")
                    continue;

                if (attribute.ConstructorArguments.Length != 1)
                {
                    diagnostic = new DiagnosticInfo(MissingExecutionMode, namedType.Locations.FirstOrDefault(), namedType.Name);
                    return false;
                }

                TypedConstant arg = attribute.ConstructorArguments[0];
                if (arg.Value is not int rawValue || !System.Enum.IsDefined(typeof(QueryExecutionMode), rawValue))
                {
                    diagnostic = new DiagnosticInfo(InvalidExecutionMode, namedType.Locations.FirstOrDefault(), namedType.Name);
                    return false;
                }

                executionMode = (QueryExecutionMode)rawValue;
                return true;
            }

            return false;
        }

        static bool HasNonBurstQueryAttribute(INamedTypeSymbol namedType)
        {
            foreach (AttributeData attribute in namedType.GetAttributes())
            {
                if (attribute.AttributeClass?.ContainingNamespace?.ToDisplayString() != "Glai.ECS")
                    continue;

                if (attribute.AttributeClass.MetadataName == "NonBurstQueryAttribute")
                    return true;
            }

            return false;
        }

        static readonly DiagnosticDescriptor InvalidExecuteSignature = new(
            id: "GLAIECS001",
            title: "Invalid query job Execute signature",
            messageFormat: "Query job '{0}' must declare {1}.",
            category: "Glai.ECS.SourceGen",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        static readonly DiagnosticDescriptor AmbiguousExecuteSignature = new(
            id: "GLAIECS002",
            title: "Ambiguous query job Execute signature",
            messageFormat: "Query job '{0}' has multiple valid Execute overloads. Keep only one supported Execute signature.",
            category: "Glai.ECS.SourceGen",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        static readonly DiagnosticDescriptor MissingExecutionMode = new(
            id: "GLAIECS003",
            title: "Missing query execution mode",
            messageFormat: "Query job '{0}' must specify a QueryExecution mode.",
            category: "Glai.ECS.SourceGen",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        static readonly DiagnosticDescriptor InvalidExecutionMode = new(
            id: "GLAIECS004",
            title: "Invalid query execution mode",
            messageFormat: "Query job '{0}' specifies an invalid QueryExecution mode.",
            category: "Glai.ECS.SourceGen",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);
    }

    enum QueryExecutionMode
    {
        MainThread,
        Async,
        ChunkParallel,
        EntityParallel,
    }

    enum AccessKind
    {
        Ref,
        Buffer,
    }

    readonly struct AccessModel : System.IEquatable<AccessModel>
    {
        public readonly AccessKind Kind;
        public readonly string AccessFullName;
        public readonly string InnerFullName;

        public AccessModel(AccessKind kind, string accessFullName, string innerFullName)
        {
            Kind = kind;
            AccessFullName = accessFullName;
            InnerFullName = innerFullName;
        }

        public bool Equals(AccessModel other)
        {
            return Kind == other.Kind
                && AccessFullName == other.AccessFullName
                && InnerFullName == other.InnerFullName;
        }

        public override int GetHashCode()
        {
            int hash = (int)Kind;
            hash = hash * 31 + (AccessFullName?.GetHashCode() ?? 0);
            hash = hash * 31 + (InnerFullName?.GetHashCode() ?? 0);
            return hash;
        }
    }

    readonly struct SystemModel : System.IEquatable<SystemModel>
    {
        public readonly string SystemName;
        public readonly string SystemFullyQualifiedName;
        public readonly string? Namespace;
        public readonly ImmutableArray<AccessModel> Accesses;
        public readonly QueryExecutionMode ExecutionMode;
        public readonly bool IsNonBurst;
        public readonly bool InjectEntityId;

        public SystemModel(string systemName, string systemFullyQualifiedName, string? ns, ImmutableArray<AccessModel> accesses, QueryExecutionMode executionMode, bool isNonBurst, bool injectEntityId)
        {
            SystemName = systemName;
            SystemFullyQualifiedName = systemFullyQualifiedName;
            Namespace = ns;
            Accesses = accesses;
            ExecutionMode = executionMode;
            IsNonBurst = isNonBurst;
            InjectEntityId = injectEntityId;
        }

        public string ExecutionModeName => $"QueryExecution.{ExecutionMode}";

        public bool Equals(SystemModel other)
        {
            if (SystemFullyQualifiedName != other.SystemFullyQualifiedName) return false;
            if (Namespace != other.Namespace) return false;
            if (ExecutionMode != other.ExecutionMode) return false;
            if (IsNonBurst != other.IsNonBurst) return false;
            if (InjectEntityId != other.InjectEntityId) return false;
            if (Accesses.Length != other.Accesses.Length) return false;
            for (int i = 0; i < Accesses.Length; i++)
            {
                if (!Accesses[i].Equals(other.Accesses[i])) return false;
            }
            return true;
        }

        public override int GetHashCode()
        {
            int hash = SystemFullyQualifiedName?.GetHashCode() ?? 0;
            hash = hash * 31 + (int)ExecutionMode;
            hash = hash * 31 + (IsNonBurst ? 1 : 0);
            hash = hash * 31 + (InjectEntityId ? 1 : 0);
            foreach (var access in Accesses)
            {
                hash = hash * 31 + access.GetHashCode();
            }
            return hash;
        }
    }

    readonly struct SystemModelResult
    {
        public readonly SystemModel? Model;
        public readonly DiagnosticInfo? Diagnostic;

        public SystemModelResult(SystemModel? model, DiagnosticInfo? diagnostic)
        {
            Model = model;
            Diagnostic = diagnostic;
        }
    }

    readonly struct ExecuteSignatureModel
    {
        public readonly ImmutableArray<AccessModel> Accesses;
        public readonly bool InjectEntityId;

        public ExecuteSignatureModel(ImmutableArray<AccessModel> accesses, bool injectEntityId)
        {
            Accesses = accesses;
            InjectEntityId = injectEntityId;
        }
    }

    readonly struct DiagnosticInfo
    {
        public readonly DiagnosticDescriptor Descriptor;
        public readonly Location? Location;
        public readonly object[] MessageArgs;

        public DiagnosticInfo(DiagnosticDescriptor descriptor, Location? location, params object[] messageArgs)
        {
            Descriptor = descriptor;
            Location = location;
            MessageArgs = messageArgs;
        }
    }
}
