using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Glai.ECS.SourceGen
{
    [Generator]
    public class SystemGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var systemModels = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is StructDeclarationSyntax sds && sds.BaseList != null,
                    transform: static (ctx, ct) => ExtractSystemModel(ctx, ct))
                .Where(static m => m != null)
                .Select(static (m, _) => m!.Value);

            context.RegisterSourceOutput(systemModels, static (spc, model) => Emit(spc, model));
        }

        static SystemModel? ExtractSystemModel(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            var structSyntax = (StructDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(structSyntax, ct);
            if (symbol is not INamedTypeSymbol namedType) return null;

            // Skip nested types — generated code can't reference private nested structs.
            if (namedType.ContainingType != null) return null;

            // Look for ISystem<T1, ...> interface implementation.
            foreach (var iface in namedType.AllInterfaces)
            {
                if (iface.OriginalDefinition.ContainingNamespace?.ToDisplayString() != "Glai.ECS")
                    continue;

                var ifaceOrigName = iface.OriginalDefinition.MetadataName;
                if (!ifaceOrigName.StartsWith("ISystem`"))
                    continue;

                var typeArgs = iface.TypeArguments;
                if (typeArgs.Length == 0 || typeArgs.Length > 7)
                    continue;

                var components = new string[typeArgs.Length];
                for (int i = 0; i < typeArgs.Length; i++)
                {
                    components[i] = typeArgs[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                }

                var ns = namedType.ContainingNamespace;
                string? namespaceName = (ns != null && !ns.IsGlobalNamespace) ? ns.ToDisplayString() : null;

                return new SystemModel(
                    namedType.Name,
                    namedType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    namespaceName,
                    components.ToImmutableArray());
            }

            return null;
        }

        static void Emit(SourceProductionContext spc, SystemModel model)
        {
            var sb = new StringBuilder(4096);
            int arity = model.ComponentFullNames.Length;
            string indent = model.Namespace != null ? "    " : "";

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using Unity.Burst;");
            sb.AppendLine("using Unity.Collections.LowLevel.Unsafe;");
            sb.AppendLine("using Unity.Jobs;");
            sb.AppendLine("using Glai.Allocator;");
            sb.AppendLine("using Glai.ECS;");
            sb.AppendLine("using Glai.ECS.Core;");
            sb.AppendLine("using Glai.Core;");
            sb.AppendLine();

            if (model.Namespace != null)
            {
                sb.AppendLine($"namespace {model.Namespace}");
                sb.AppendLine("{");
            }

            // ── ChunkData Struct ────────────────────────────────────────────
            sb.AppendLine($"{indent}[StructLayout(LayoutKind.Sequential)]");
            sb.AppendLine($"{indent}internal unsafe struct {model.SystemName}__ChunkData");
            sb.AppendLine($"{indent}{{");
            for (int i = 0; i < arity; i++)
                sb.AppendLine($"{indent}    public byte* c{i};");
            sb.AppendLine($"{indent}    public int entityCount;");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();

            // ── IJobParallelFor Struct ──────────────────────────────────────
            sb.AppendLine($"{indent}[BurstCompile]");
            sb.AppendLine($"{indent}internal unsafe struct {model.SystemName}__Job : IJobParallelFor");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public {model.SystemFullyQualifiedName} System;");
            sb.AppendLine($"{indent}    [NativeDisableUnsafePtrRestriction] public {model.SystemName}__ChunkData* Chunks;");
            sb.AppendLine();

            // Execute(int index)
            sb.AppendLine($"{indent}    public void Execute(int index)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        ref var data = ref Chunks[index];");
            var burstCallArgs = new StringBuilder();
            burstCallArgs.Append("ref System");
            for (int i = 0; i < arity; i++)
                burstCallArgs.Append($", data.c{i}");
            burstCallArgs.Append(", data.entityCount");
            sb.AppendLine($"{indent}        ExecuteChunkBurst({burstCallArgs});");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // ExecuteChunkBurst — the [BurstCompile] static entry point
            sb.AppendLine($"{indent}    [BurstCompile]");
            var burstParams = new StringBuilder();
            burstParams.Append($"ref {model.SystemFullyQualifiedName} system");
            for (int i = 0; i < arity; i++)
                burstParams.Append($", byte* c{i}");
            burstParams.Append(", int count");
            sb.AppendLine($"{indent}    internal static void ExecuteChunkBurst({burstParams})");
            sb.AppendLine($"{indent}    {{");

            // Cast byte pointers to typed pointers
            for (int i = 0; i < arity; i++)
                sb.AppendLine($"{indent}        {model.ComponentFullNames[i]}* p{i} = ({model.ComponentFullNames[i]}*)c{i};");

            // 4x unrolled main loop
            sb.AppendLine($"{indent}        int stop = count & ~3;");
            sb.AppendLine($"{indent}        for (int i = 0; i < stop; i += 4)");
            sb.AppendLine($"{indent}        {{");
            for (int u = 0; u < 4; u++)
            {
                var execArgsU = new StringBuilder();
                for (int i = 0; i < arity; i++)
                {
                    if (i > 0) execArgsU.Append(", ");
                    execArgsU.Append($"ref p{i}[i + {u}]");
                }
                sb.AppendLine($"{indent}            system.Execute({execArgsU});");
            }
            sb.AppendLine($"{indent}        }}");

            // Scalar remainder
            sb.AppendLine($"{indent}        for (int i = stop; i < count; i++)");
            sb.AppendLine($"{indent}        {{");
            var execArgs = new StringBuilder();
            for (int i = 0; i < arity; i++)
            {
                if (i > 0) execArgs.Append(", ");
                execArgs.Append($"ref p{i}[i]");
            }
            sb.AppendLine($"{indent}            system.Execute({execArgs});");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");

            sb.AppendLine($"{indent}}}"); // end __Job struct
            sb.AppendLine();

            // ── Dispatch Struct ─────────────────────────────────────────────
            sb.AppendLine($"{indent}internal unsafe struct {model.SystemName}__Dispatch : global::Glai.ECS.ISystemDispatch");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public {model.SystemFullyQualifiedName} System;");
            sb.AppendLine();

            // Storage indices
            for (int i = 0; i < arity; i++)
                sb.AppendLine($"{indent}    private int _s{i};");
            sb.AppendLine();

            // Arena fields
            sb.AppendLine($"{indent}    private {model.SystemName}__ChunkData* _chunkDataPtr;");
            sb.AppendLine();

            // Prepare
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    public void Prepare(global::Glai.Allocator.MemoryStateHandle arenaHandle, global::Glai.ECS.Core.ECSMemoryState memoryState, int maxChunks)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var allocator = memoryState.GetAllocator(arenaHandle);");
            sb.AppendLine($"{indent}        var arrayHandle = allocator.AllocateArray<{model.SystemName}__ChunkData>(maxChunks);");
            sb.AppendLine($"{indent}        var chunkDataSpan = allocator.GetArray<{model.SystemName}__ChunkData>(arrayHandle);");
            sb.AppendLine($"{indent}        fixed ({model.SystemName}__ChunkData* chunkDataPtr = chunkDataSpan)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            _chunkDataPtr = chunkDataPtr;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // PrepareArchetype
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    public bool PrepareArchetype(ref global::Glai.ECS.Core.Archetype archetype)");
            sb.AppendLine($"{indent}    {{");
            for (int i = 0; i < arity; i++)
                sb.AppendLine($"{indent}        _s{i} = archetype.GetComponentStorageIndex(global::Glai.Core.TypeId<{model.ComponentFullNames[i]}>.Id);");
            var failCheck = string.Join(" || ", Enumerable.Range(0, arity).Select(i => $"_s{i} == -1"));
            sb.AppendLine($"{indent}        if ({failCheck}) return false;");
            sb.AppendLine($"{indent}        return true;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // CollectChunk
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    public void CollectChunk(ref global::Glai.ECS.Core.Chunk chunk, int chunkIndex)");
            sb.AppendLine($"{indent}    {{");
            for (int i = 0; i < arity; i++)
                sb.AppendLine($"{indent}        _chunkDataPtr[chunkIndex].c{i} = chunk.GetComponentPtr(_s{i});");
            sb.AppendLine($"{indent}        _chunkDataPtr[chunkIndex].entityCount = chunk.EntityCount;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // ScheduleParallel
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    public global::Unity.Jobs.JobHandle ScheduleParallel(int chunkCount)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var job = new {model.SystemName}__Job");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            System = this.System,");
            sb.AppendLine($"{indent}            Chunks = _chunkDataPtr,");
            sb.AppendLine($"{indent}        }};");
            sb.AppendLine($"{indent}        return job.Schedule(chunkCount, 1);");
            sb.AppendLine($"{indent}    }}");

            sb.AppendLine($"{indent}}}"); // end dispatch struct
            sb.AppendLine();

            // ── Extension Method ────────────────────────────────────────────
            sb.AppendLine($"{indent}internal static class {model.SystemName}__Extensions");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public static global::Glai.ECS.SystemHandle Run(this global::Glai.ECS.EntityManager em, global::Glai.ECS.QueryBuilder query, ref {model.SystemFullyQualifiedName} system)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var dispatch = new {model.SystemName}__Dispatch {{ System = system }};");
            sb.AppendLine($"{indent}        var handle = em.Run(query, ref dispatch);");
            sb.AppendLine($"{indent}        system = dispatch.System;");
            sb.AppendLine($"{indent}        return handle;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (model.Namespace != null)
                sb.AppendLine("}"); // end namespace

            spc.AddSource($"{model.SystemName}__Generated.g.cs", sb.ToString());
        }
    }

    readonly struct SystemModel : System.IEquatable<SystemModel>
    {
        public readonly string SystemName;
        public readonly string SystemFullyQualifiedName;
        public readonly string? Namespace;
        public readonly ImmutableArray<string> ComponentFullNames;

        public SystemModel(string systemName, string systemFullyQualifiedName, string? ns, ImmutableArray<string> componentFullNames)
        {
            SystemName = systemName;
            SystemFullyQualifiedName = systemFullyQualifiedName;
            Namespace = ns;
            ComponentFullNames = componentFullNames;
        }

        public bool Equals(SystemModel other)
        {
            if (SystemFullyQualifiedName != other.SystemFullyQualifiedName) return false;
            if (Namespace != other.Namespace) return false;
            if (ComponentFullNames.Length != other.ComponentFullNames.Length) return false;
            for (int i = 0; i < ComponentFullNames.Length; i++)
                if (ComponentFullNames[i] != other.ComponentFullNames[i]) return false;
            return true;
        }

        public override int GetHashCode()
        {
            int hash = SystemFullyQualifiedName?.GetHashCode() ?? 0;
            foreach (var c in ComponentFullNames)
                hash = hash * 31 + (c?.GetHashCode() ?? 0);
            return hash;
        }
    }
}
