using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Glai.ECS.SourceGen
{
    [Generator]
    public class QueryJobGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var jobModels = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is StructDeclarationSyntax sds && sds.BaseList != null,
                    transform: static (ctx, ct) => ExtractJobModel(ctx, ct))
                .Where(static m => m != null)
                .Select(static (m, _) => m!.Value);

            context.RegisterSourceOutput(jobModels, static (spc, model) => Emit(spc, model));
        }

        static QueryJobModel? ExtractJobModel(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            var structSyntax = (StructDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(structSyntax, ct);
            if (symbol is not INamedTypeSymbol namedType) return null;

            // Skip nested types — generated code can't reference private nested structs.
            if (namedType.ContainingType != null) return null;

            // Look for IQueryJob<T1, ...> interface implementation.
            foreach (var iface in namedType.AllInterfaces)
            {
                if (iface.OriginalDefinition.ContainingNamespace?.ToDisplayString() != "Glai.ECS")
                    continue;

                var ifaceOrigName = iface.OriginalDefinition.MetadataName;
                if (!ifaceOrigName.StartsWith("IQueryJob`"))
                    continue;

                var typeArgs = iface.TypeArguments;
                if (typeArgs.Length == 0 || typeArgs.Length > 7)
                    continue;

                var components = new string[typeArgs.Length];
                for (int i = 0; i < typeArgs.Length; i++)
                {
                    components[i] = typeArgs[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                }

                var ns = namedType.ContainingNamespace;
                string? namespaceName = (ns != null && !ns.IsGlobalNamespace) ? ns.ToDisplayString() : null;

                return new QueryJobModel(
                    namedType.Name,
                    namedType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    namespaceName,
                    components.ToImmutableArray());
            }

            return null;
        }

        static void Emit(SourceProductionContext spc, QueryJobModel model)
        {
            var sb = new StringBuilder(2048);
            int arity = model.ComponentFullNames.Length;
            string indent = model.Namespace != null ? "    " : "";

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using Unity.Burst;");
            sb.AppendLine("using Glai.ECS.Core;");
            sb.AppendLine("using Glai.Core;");
            sb.AppendLine();

            if (model.Namespace != null)
            {
                sb.AppendLine($"namespace {model.Namespace}");
                sb.AppendLine("{");
            }

            // ── Dispatch Struct ───────────────────────────────────────────────
            sb.AppendLine($"{indent}[BurstCompile]");
            sb.AppendLine($"{indent}internal unsafe struct {model.JobName}__Dispatch : global::Glai.ECS.IQueryJobDispatch");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public {model.JobFullyQualifiedName} Job;");

            for (int i = 0; i < arity; i++)
                sb.AppendLine($"{indent}    private int _s{i};");

            sb.AppendLine();

            // PrepareArchetype
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    public bool PrepareArchetype(ref global::Glai.ECS.Core.Archetype archetype)");
            sb.AppendLine($"{indent}    {{");
            for (int i = 0; i < arity; i++)
                sb.AppendLine($"{indent}        _s{i} = archetype.GetComponentStorageIndex(global::Glai.Core.TypeId<{model.ComponentFullNames[i]}>.Id);");
            var failCheck = string.Join(" || ", Enumerable.Range(0, arity).Select(i => $"_s{i} == -1"));
            sb.AppendLine($"{indent}        if ({failCheck}) return false;");
            sb.AppendLine($"{indent}        return true;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // ExecuteChunk
            sb.AppendLine($"{indent}    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"{indent}    public void ExecuteChunk(ref global::Glai.ECS.Core.Chunk chunk)");
            sb.AppendLine($"{indent}    {{");
            var chunkArgs = new StringBuilder();
            chunkArgs.Append("ref Job");
            for (int i = 0; i < arity; i++)
                chunkArgs.Append($", chunk.GetComponentPtr(_s{i})");
            chunkArgs.Append(", chunk.EntityCount");
            sb.AppendLine($"{indent}        ExecuteChunkBurst({chunkArgs});");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // ExecuteChunkBurst — the [BurstCompile] entry point (concrete, non-generic)
            // Uses typed pointer casts instead of runtime strides so LLVM can vectorize.
            sb.AppendLine($"{indent}    [BurstCompile]");
            var burstParams = new StringBuilder();
            burstParams.Append($"ref {model.JobFullyQualifiedName} job");
            for (int i = 0; i < arity; i++)
                burstParams.Append($", byte* c{i}");
            burstParams.Append(", int count");
            sb.AppendLine($"{indent}    internal static void ExecuteChunkBurst({burstParams})");
            sb.AppendLine($"{indent}    {{");

            // Cast byte pointers to typed pointers — compile-time element size enables vectorization
            for (int i = 0; i < arity; i++)
                sb.AppendLine($"{indent}        {model.ComponentFullNames[i]}* p{i} = ({model.ComponentFullNames[i]}*)c{i};");

            // 4x unrolled main loop — wider scheduling window helps LLVM/Burst vectorize
            sb.AppendLine($"{indent}        int stop = count & ~3;");
            sb.AppendLine($"{indent}        for (int i = 0; i < stop; i += 4)");
            sb.AppendLine($"{indent}        {{");
            for (int u = 0; u < 4; u++)
            {
                var execArgsU = new StringBuilder();
                for (int i = 0; i < arity; i++)
                {
                    if (i > 0) execArgsU.Append(", ");
                    execArgsU.Append($"ref p{i}[i + {u}]");
                }
                sb.AppendLine($"{indent}            job.Execute({execArgsU});");
            }
            sb.AppendLine($"{indent}        }}");

            // Scalar remainder
            sb.AppendLine($"{indent}        for (int i = stop; i < count; i++)");
            sb.AppendLine($"{indent}        {{");
            var execArgs = new StringBuilder();
            for (int i = 0; i < arity; i++)
            {
                if (i > 0) execArgs.Append(", ");
                execArgs.Append($"ref p{i}[i]");
            }
            sb.AppendLine($"{indent}            job.Execute({execArgs});");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");

            sb.AppendLine($"{indent}}}"); // end dispatch struct
            sb.AppendLine();

            // ── Extension Method ──────────────────────────────────────────────
            sb.AppendLine($"{indent}internal static class {model.JobName}__Extensions");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public static void Run(this global::Glai.ECS.EntityManager em, global::Glai.ECS.QueryBuilder query, ref {model.JobFullyQualifiedName} job)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var dispatch = new {model.JobName}__Dispatch {{ Job = job }};");
            sb.AppendLine($"{indent}        em.Run(query, ref dispatch);");
            sb.AppendLine($"{indent}        job = dispatch.Job;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (model.Namespace != null)
                sb.AppendLine("}"); // end namespace

            spc.AddSource($"{model.JobName}__Generated.g.cs", sb.ToString());
        }
    }

    readonly struct QueryJobModel : System.IEquatable<QueryJobModel>
    {
        public readonly string JobName;
        public readonly string JobFullyQualifiedName;
        public readonly string? Namespace;
        public readonly ImmutableArray<string> ComponentFullNames;

        public QueryJobModel(string jobName, string jobFullyQualifiedName, string? ns, ImmutableArray<string> componentFullNames)
        {
            JobName = jobName;
            JobFullyQualifiedName = jobFullyQualifiedName;
            Namespace = ns;
            ComponentFullNames = componentFullNames;
        }

        public bool Equals(QueryJobModel other)
        {
            if (JobFullyQualifiedName != other.JobFullyQualifiedName) return false;
            if (Namespace != other.Namespace) return false;
            if (ComponentFullNames.Length != other.ComponentFullNames.Length) return false;
            for (int i = 0; i < ComponentFullNames.Length; i++)
                if (ComponentFullNames[i] != other.ComponentFullNames[i]) return false;
            return true;
        }

        public override int GetHashCode()
        {
            int hash = JobFullyQualifiedName?.GetHashCode() ?? 0;
            foreach (var c in ComponentFullNames)
                hash = hash * 31 + (c?.GetHashCode() ?? 0);
            return hash;
        }
    }
}
